// examples/react-dashboard/src/pages/Dashboard.jsx
import useDashboardStore from '../stores/useDashboardStore';
import Card from '../components/Card';
import DataTable from '../components/DataTable';
import './Dashboard.scss';

export default function Dashboard() {
  const { stats, transactions } = useDashboardStore();

  return (
    /* Outer: just fills space, no layout props */
    <div className="dashboard">
      {/* Inner: flex column with gap */}
      <div className="dashboard__inner">
        <h1 className="dashboard__heading">Overview</h1>
        {/* Inner: grid for stat cards */}
        <div className="dashboard__cards">
          {stats.map((stat) => (
            <Card key={stat.id} stat={stat} />
          ))}
        </div>
        {/* Inner for table section */}
        <div className="dashboard__tableSection">
          <h2 className="dashboard__subheading">Recent Transactions</h2>
          <DataTable transactions={transactions} />
        </div>
      </div>
    </div>
  );
}

// examples/vue-dashboard/src/pages/Dashboard.vue
<template>
  <div class="dashboard">
    <div class="dashboard__inner">
      <div class="dashboard__cards">
        <Card
          v-for="stat in store.stats"
          :key="stat.title"
          :title="stat.title"
          :value="stat.value"
          :change="stat.change"
          :trend="stat.trend"
        />
      </div>
      <div class="dashboard__table">
        <DataTable :data="store.tableData" />
      </div>
    </div>
  </div>
</template>

<script setup>
import { useDashboardStore } from '../stores/dashboard'
import Card from '../components/Card.vue'
import DataTable from '../components/DataTable.vue'

const store = useDashboardStore()
</script>

<style src="./Dashboard.scss" scoped></style>
