// examples/react-dashboard/src/components/Card.jsx
import './Card.scss';

export default function Card({ stat }) {
  const { label, value, change, trend } = stat;
  const isUp = trend === 'up';

  return (
    /* Outer: background/border ONLY */
    <article className="card">
      {/* Inner: flex column + padding + gap */}
      <div className="card__inner">
        <span className="card__label">{label}</span>
        <span className="card__value">{value}</span>
        <span
          className={
            'card__change' +
            (isUp ? ' card__change--up' : ' card__change--down')
          }
        >
          {change}
        </span>
      </div>
    </article>
  );
}

// examples/vue-dashboard/src/components/Card.vue
<template>
  <div class="card">
    <div class="card__inner">
      <div class="card__header">
        <span class="card__title">{{ title }}</span>
      </div>
      <div class="card__body">
        <span class="card__value">{{ value }}</span>
        <span
          class="card__change"
          :class="`card__change--${trend}`"
        >
          {{ change }}
        </span>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  title: { type: String, required: true },
  value: { type: String, required: true },
  change: { type: String, required: true },
  trend: { type: String, default: 'up' },
})
</script>

<style src="./Card.scss" scoped></style>
