// examples/vue-dashboard/src/components/DataTable.vue
<template>
  <div class="data-table">
    <div class="data-table__inner">
      <div class="data-table__header">
        <h3 class="data-table__title">Recent Transactions</h3>
      </div>
      <div class="data-table__wrapper">
        <table class="data-table__table">
          <colgroup>
            <col style="width: 20%" />
            <col style="width: 30%" />
            <col style="width: 20%" />
            <col style="width: 15%" />
            <col style="width: 15%" />
          </colgroup>
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in data" :key="row.id">
              <td class="data-table__cell--name">{{ row.name }}</td>
              <td>{{ row.email }}</td>
              <td>{{ row.role }}</td>
              <td>
                <span
                  class="data-table__status"
                  :class="`data-table__status--${row.status.toLowerCase()}`"
                >
                  {{ row.status }}
                </span>
              </td>
              <td>
                <button class="data-table__action">Edit</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  data: { type: Array, required: true },
})
</script>

<style src="./DataTable.scss" scoped></style>

// examples/react-dashboard/src/components/DataTable/DataTable.jsx
import './DataTable.scss';

const data = [
  { name: 'Alice Johnson', email: 'alice@example.com', amount: '$320.00', status: 'Completed' },
  { name: 'Bob Smith', email: 'bob@example.com', amount: '$150.00', status: 'Pending' },
  { name: 'Carol White', email: 'carol@example.com', amount: '$480.00', status: 'Completed' },
  { name: 'Dan Brown', email: 'dan@example.com', amount: '$210.00', status: 'Cancelled' },
  { name: 'Eve Davis', email: 'eve@example.com', amount: '$645.00', status: 'Completed' },
  { name: 'Frank Miller', email: 'frank@example.com', amount: '$95.00', status: 'Pending' },
];

export default function DataTable() {
  return (
    <div className="data-table">
      <div className="data-table__inner">
        <div className="data-table__header">
          <h3>Recent Orders</h3>
          <span className="data-table__view-all">View All</span>
        </div>
        <div className="data-table__scroll">
          <table>
            <thead>
              <tr>
                <th>Customer</th>
                <th>Email</th>
                <th>Amount</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {data.map((row) => (
                <tr key={row.email}>
                  <td>{row.name}</td>
                  <td className="data-table__email">{row.email}</td>
                  <td>{row.amount}</td>
                  <td>
                    <span className={`data-table__status data-table__status--${row.status.toLowerCase()}`}>
                      {row.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
