// examples/react-dashboard/src/layout/AppShell.jsx
import { useRoutes } from 'react-router-dom';
import NavBar from './NavBar';
import Sidebar from './Sidebar';
import routes from '../routes';
import './AppShell.scss';

export default function AppShell() {
  const element = useRoutes(routes);

  return (
    /* Outer: background/border ONLY */
    <div className="shell">
      {/* Inner: flex row, full height */}
      <div className="shell__inner">
        <Sidebar />
        {/* Inner: flex column for navbar + content */}
        <div className="shell__main">
          <NavBar />
          {/* Child: overflow:auto, no margin */}
          <main className="shell__content">
            {element}
          </main>
        </div>
      </div>
    </div>
  );
}

// examples/vue-dashboard/src/layout/AppShell.vue
<template>
  <div class="app-shell">
    <div class="app-shell__inner">
      <Sidebar />
      <div class="app-shell__main">
        <NavBar />
        <main class="app-shell__content">
          <router-view />
        </main>
      </div>
    </div>
  </div>
</template>

<script setup>
import Sidebar from './Sidebar.vue'
import NavBar from './NavBar.vue'
</script>

<style src="./AppShell.scss" scoped></style>
