// examples/react-dashboard/src/layout/NavBar.jsx
import './NavBar.scss';

export default function NavBar() {
  return (
    /* Outer: background/border ONLY */
    <header className="navbar">
      {/* Inner: flex row with padding + gap */}
      <div className="navbar__inner">
        <div className="navbar__left">
          <h2 className="navbar__title">Dashboard</h2>
        </div>
        <div className="navbar__right">
          <input type="text" className="navbar__search" placeholder="Search..." />
          <div className="navbar__avatar">JD</div>
        </div>
      </div>
    </header>
  );
}

// examples/vue-dashboard/src/layout/NavBar.vue
<template>
  <header class="navbar">
    <div class="navbar__inner">
      <h2 class="navbar__title">Dashboard</h2>
      <div class="navbar__actions">
        <div class="navbar__search">
          <input
            type="text"
            placeholder="Search..."
            class="navbar__input"
          />
        </div>
        <div class="navbar__avatar">U</div>
      </div>
    </div>
  </header>
</template>

<script setup>
</script>

<style src="./NavBar.scss" scoped></style>
