// examples/react-dashboard/src/layout/Sidebar.jsx
import { useState } from 'react';
import './Sidebar.scss';

const navItems = [
  { id: 'dashboard', label: 'Dashboard', icon: '\u{1F4CA}' },
  { id: 'analytics', label: 'Analytics', icon: '\u{1F4C8}' },
  { id: 'users', label: 'Users', icon: '\u{1F465}' },
  { id: 'orders', label: 'Orders', icon: '\u{1F4E6}' },
  { id: 'settings', label: 'Settings', icon: '⚙️' },
];

export default function Sidebar() {
  const [active, setActive] = useState('dashboard');

  return (
    /* Outer: background/border ONLY */
    <aside className="sidebar">
      {/* Inner: flex column */}
      <div className="sidebar__inner">
        <div className="sidebar__brand">
          <span className="sidebar__logo">DS</span>
          <span className="sidebar__brandName">DashStack</span>
        </div>
        <nav className="sidebar__nav">
          {navItems.map((item) => (
            <button
              key={item.id}
              className={
                'sidebar__item' +
                (active === item.id ? ' sidebar__item--active' : '')
              }
              onClick={() => setActive(item.id)}
            >
              <span className="sidebar__icon">{item.icon}</span>
              <span className="sidebar__label">{item.label}</span>
            </button>
          ))}
        </nav>
      </div>
    </aside>
  );
}

// examples/vue-dashboard/src/layout/Sidebar.vue
<template>
  <aside class="sidebar">
    <div class="sidebar__inner">
      <div class="sidebar__header">
        <span class="sidebar__logo">DivSkill</span>
      </div>
      <nav class="sidebar__nav">
        <router-link
          v-for="link in store.sidebarLinks"
          :key="link.label"
          :to="link.route"
          class="sidebar__link"
        >
          <span class="sidebar__icon">{{ link.icon }}</span>
          <span class="sidebar__label">{{ link.label }}</span>
        </router-link>
      </nav>
    </div>
  </aside>
</template>

<script setup>
import { useDashboardStore } from '../stores/dashboard'

const store = useDashboardStore()
</script>

<style src="./Sidebar.scss" scoped></style>
