// examples/react-dashboard/src/components/Sidebar/Sidebar.jsx
import './Sidebar.scss';

const menuItems = [
  { icon: '⌂', label: 'Overview', active: true },
  { icon: '□', label: 'Analytics' },
  { icon: '☰', label: 'Orders' },
  { icon: '★', label: 'Customers' },
];

const secondaryItems = [
  { icon: '⚙', label: 'Settings' },
  { icon: '❓', label: 'Help' },
];

export default function Sidebar() {
  return (
    <aside className="sidebar">
      <div className="sidebar__inner">
        <div className="sidebar__section-title">Main Menu</div>
        {menuItems.map((item) => (
          <div
            key={item.label}
            className={`sidebar__item${item.active ? ' sidebar__item--active' : ''}`}
          >
            <span className="sidebar__item-icon">{item.icon}</span>
            <span className="sidebar__item-label">{item.label}</span>
          </div>
        ))}
        <div className="sidebar__divider" />
        {secondaryItems.map((item) => (
          <div key={item.label} className="sidebar__item">
            <span className="sidebar__item-icon">{item.icon}</span>
            <span className="sidebar__item-label">{item.label}</span>
          </div>
        ))}
      </div>
    </aside>
  );
}

// src/layout/Sidebar/Sidebar.vue
<template>
  <div class="sidebar__outer">
    <div class="sidebar__inner">
      <nav class="sidebar__nav">
        <a
          v-for="item in navItems"
          :key="item.label"
          class="sidebar__item"
          :class="{ 'sidebar__item--active': item.active }"
          href="#"
        >
          <span class="sidebar__icon">{{ item.icon }}</span>
          <span class="sidebar__label">{{ item.label }}</span>
        </a>
      </nav>
    </div>
  </div>
</template>

<script setup>
const navItems = [
  { icon: '⌂', label: 'Dashboard', active: true },
  { icon: '☰', label: 'Analytics', active: false },
  { icon: '⚙', label: 'Settings', active: false },
  { icon: 'ℹ', label: 'Help', active: false }
]
</script>

<style src="./Sidebar.scss" />
