// examples/react-dashboard/src/components/StatCard/StatCard.jsx
import './StatCard.scss';

export default function StatCard({ label, value, change, changeUp, icon, iconClass }) {
  return (
    <div className="stat-card">
      <div className="stat-card__inner">
        <div className="stat-card__top">
          <div className="stat-card__info">
            <div className="stat-card__label">{label}</div>
            <div className="stat-card__value">{value}</div>
          </div>
          <div className={`stat-card__icon ${iconClass}`}>{icon}</div>
        </div>
        <div className={`stat-card__change ${changeUp ? 'stat-card__change--up' : 'stat-card__change--down'}`}>
          {change}
        </div>
      </div>
    </div>
  );
}

// examples/vue-dashboard/src/components/StatCard/StatCard.vue
<template>
  <div class="stat-card">
    <div class="stat-card__inner">
      <span class="stat-card__label">{{ label }}</span>
      <span class="stat-card__value">{{ value }}</span>
      <span
        class="stat-card__change"
        :class="{ 'stat-card__change--negative': isNegative }"
      >{{ change }}</span>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  label: { type: String, required: true },
  value: { type: String, required: true },
  change: { type: String, required: true },
})

const isNegative = computed(() => props.change.startsWith('-'))
</script>

<style src="./StatCard.scss"></style>
